### ISSUE TITLE
gulp public = "File Not Found" error on syntaxhighlighter.js

### ISSUE THREAD

**Issue by tsconn23** [PioneerCode/pioneer-blog#96]
When I run "gulp public" I receive the following error.

[14:05:55] Error: File not found with singular glob: D:\Git\tsconn23\pioneer-blog\src\Pioneer.Blog\scripts\syntaxhighlighter.js
    at Glob.<anonymous> (D:\Git\tsconn23\pioneer-blog\src\Pioneer.Blog\node_modules\glob-stream\index.js:41:11)
    at Glob.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:188:7)
    at Glob._finish (D:\Git\tsconn23\pioneer-blog\src\Pioneer.Blog\node_modules\glob-stream\node_modules\glob\glob.js:172:8)
    at done (D:\Git\tsconn23\pioneer-blog\src\Pioneer.Blog\node_modules\glob-stream\node_modules\glob\glob.js:159:12)
    at Glob._processSimple2 (D:\Git\tsconn23\pioneer-blog\src\Pioneer.Blog\node_modules\glob-stream\node_modules\glob\glob.js:652:12)
    at D:\Git\tsconn23\pioneer-blog\src\Pioneer.Blog\node_modules\glob-stream\node_modules\glob\glob.js:640:10
    at Glob._stat2 (D:\Git\tsconn23\pioneer-blog\src\Pioneer.Blog\node_modules\glob-stream\node_modules\glob\glob.js:736:12)
    at lstatcb_ (D:\Git\tsconn23\pioneer-blog\src\Pioneer.Blog\node_modules\glob-stream\node_modules\glob\glob.js:728:12)
    at RES (D:\Git\tsconn23\pioneer-blog\src\Pioneer.Blog\node_modules\inflight\inflight.js:31:16)
    at f (D:\Git\tsconn23\pioneer-blog\src\Pioneer.Blog\node_modules\once\once.js:25:25)
    at FSReqWrap.oncomplete (fs.js:123:15)

This appears to be due to the inclusion of a pre-built 'scripts/syntaxhighlighter.js' entry in gulp-tasks\public.js (line 77). However that file is not checked into src.

To get around this, one can go to the repo for [syntaxhighlighter.js](https://github.com/syntaxhighlighter/syntaxhighlighter/wiki/Building) and build a local copy which can then be placed in Pioneer.Blog\scripts. But inclusion of the pre-built file would make things easier for someone just looking to try out PioneerBlog.

**Comment by chad-ramos** [comment]
@tsconn23 

I agree.  Build a syntaxhighlighter file is a challenge in itself.  I will add it tomorrow morning.

Thanks,

Chad

**Comment by chad-ramos** [comment]
@tsconn23 Just pushed the scripts folder 4519add3a18d4cf45d1fea26be82d7b13140a7b5
